// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgwhtfaflfvtjmxlccuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnd2h0ZmFmbGZ2dGpteGxjY3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDEwODEsImV4cCI6MjA2MDgxNzA4MX0.w16J-9fybpE5QBd2L6uIFx23u9qDhJRcGTNpishvzu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);